name: DockerHub Build & Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: docker build -t ${{ inputs.service_name }}:latest .
      - run: |
          docker tag ${{ inputs.service_name }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:latest
